name: ai_affiliate_android
description: Aplikasi Otomatisasi Video Affiliate Menggunakan AI Gemini.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  ffmpeg_kit_flutter_video: ^6.0.3 # Diubah ke varian video agar aman di Android
  file_picker: ^8.0.0

flutter:
  uses-material-design: true
