name: Pabrik Pembuat APK Otomatis

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.x'
        channel: 'stable'

    - name: Generate Folder Android Otomatis
      run: flutter create . --platforms=android

    - name: Suntik Konfigurasi Maven & SDK (Solusi Kunci FFmpeg)
      run: |
        # 1. Paksa sistem menggunakan minSdkVersion 24 di build.gradle utama aplikasi
        sed -i 's/minSdkVersion .*/minSdkVersion 24/g' android/app/build.gradle
        sed -i 's/flutter.minSdkVersion/24/g' android/app/build.gradle || true
        
        # 2. Tulis ulang file android/build.gradle secara total agar server mavenCentral() diprioritaskan
        cat << 'EOF' > android/build.gradle
        allprojects {
            repositories {
                google()
                mavenCentral()
            }
        }

        rootProject.buildDir = '../build'
        subprojects {
            project.buildDir = "${rootProject.buildDir}/${project.name}"
        }
        subprojects {
            project.evaluationDependsOn(':app')
        }

        tasks.register("clean", Delete) {
            delete rootProject.buildDir
        }
        EOF

    - name: Ambil Dependency Proyek
      run: flutter pub get

    - name: Compile Jadi APK Android
      run: flutter build apk --release --no-tree-shake-icons

    - name: Simpan Hasil APK Akhir
      uses: actions/upload-artifact@v4
      with:
        name: Aplikasi-AI-Affiliate-Matang
        path: build/app/outputs/flutter-apk/app-release.apk
