name: Pabrik Pembuat APK Otomatis

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.x'
        channel: 'stable'

    - name: Cabut Modul FFmpeg & Bersihkan Pondasi (Plan B)
      run: |
        rm -rf android
        flutter create . --platforms=android --org com.example
        
        # Hapus secara otomatis plugin usang yang menyebabkan error 26 kali
        sed -i '/ffmpeg_kit_flutter/d' pubspec.yaml

    - name: Ambil Dependency Proyek
      run: flutter pub get

    - name: Compile Jadi APK Android
      run: flutter build apk --release --no-tree-shake-icons

    - name: Simpan Hasil APK Akhir
      uses: actions/upload-artifact@v4
      with:
        name: Aplikasi-AI-Affiliate-Matang
        path: build/app/outputs/flutter-apk/app-release.apk
